name: Deploy to Amazon EC2

on:
  push:
    branches:
      - master

# 본인이 설정한 값을 여기서 채워넣습니다.
# 리전, 버킷 이름, CodeDeploy 앱 이름, CodeDeploy 배포 그룹 이름
env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: mini-operation-project-8-bucket
  CODE_DEPLOY_APPLICATION_NAME: my-codedeploy-app
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: my-codedeplroy-deployment-group
  PROJECT_NAME: cooperation_project

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          # 사용하는 자바 버전 17
          java-version: '17'
          distribution: 'temurin'
 
      # gradlew에 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      # gradlew 빌드
      - name: Build with Gradle
        run: ./gradlew clean build --exclude-task test

      # 압축파일 형태로 전달
      - name: Make zip file
        run: zip -r ./cooperation_project.zip .
        shell: bash
        

      # S3 Bucket으로 Copy
      - name: Deliver to AWS S3
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./cooperation_project.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/cooperation_project.zip

      # Deploy
      # applicatio-name => aws code deploy application 이름
      - name: Deploy
        run: |
          aws deploy create-deployment \
          --application-name mini-operation-project-8 \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name Code Deploy my-codedeplroy-deployment-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=S3 mini-operation-project-8-bucket,bundleType=zip,key=cooperation_project/cooperation_project.zip \
          --region ap-northeast-2 \
